name: 西安暘普信息技术
email: jutleo@gmail.com
markdown: redcarpet
pygments: false
permalink: /:year/:month/:day/:title
encoding: utf-8
#每页文章数
paginate: 9

author:
  name: leo
  email: jutleo@gmail.com
menuitems:
- name:     首页
  subName:  []
  url:      /
  class:    leo-nav-item
- name:     试用
  subName:  []
  url:      /2014/02/14/newscenter
  class:    leo-nav-item
- name:     产品
  subName:  [餐饮软件#/2014/02/14/cateringsoftcenter,酒店软件#/2014/02/14/hotelcenter,配套硬件#/2014/02/14/hardwarecenter]
  url:      /
  class:    leo-nav-item
- name:     咨询
  subName:  []
  url:      /2014/02/14/industrycenter
  class:    leo-nav-item
- name:     服务
  subName:  []
  url:      /2014/02/14/integrationcenter
  class:    leo-nav-item
- name:     案例
  subName:  []
  url:      /2014/02/14/solutioncenter
  class:    leo-nav-item
- name:     交流
  subName:  []
  url:      /2014/02/14/baikecenter
  class:    leo-nav-item
- name:     关于暘普
  subName:  []
  url:      /contant.html
  url:      /2014/02/14/aboutcenter
  class:    leo-nav-item
pageCatalog:
- name:     方案中心
  code:     solution
- name:     新闻中心
  code:     news
- name:     软件
  code:     soft
- name:     硬件
  code:     hardware
- name:     服务
  code:     service
- name:     快速通道
  code:     away
- name:     最新案例
  code:     casex
- name:     行业资讯
  code:     industry
- name:     品牌活动
  code:     brand

bannerConfig:
- imgs: cybt.jpg
  text: 
- imgs: cyt1.jpg
  text: 
- imgs: sy01.jpg
  text: 
- imgs: syjd02.jpg
  text: 
- imgs: jiudweixin.jpg
  text: 

  homeDescText1: 我们的优势  
homeDesc1:
- imgs: round.gif
  text1: 餐饮行业
  text2: 无线点菜软件,触摸屏点菜软件,平板点菜软件、餐饮管理软件、连锁餐饮软件。
- imgs: round.gif
  text1: 酒店宾馆行业
  text2: 快捷酒店软件,宾馆管理软件,综合星级酒店软件,连锁酒店一卡通软件。
- imgs: round.gif
  text1: 洗浴娱乐行业
  text2: 洗浴管理软件、足浴管理软件。
- imgs: round.gif
  text1: 零售百货行业
  text2: 超市软件、零售进销存软件、行业管理软件、分销管理软件。

homeDescText2: 我们的优势
homeDesc2:
- imgs: canyin.jpg
  text1: 餐饮行业软件
  text2: 咨询服务
- imgs: jiudian.jpg
  text1: 酒店宾馆行业软件
  text2: 咨询服务
- imgs: jd.jpg
  text1: 洗浴娱乐行业软件
  text2: 咨询服务

homeDescText3: 我们竭诚为您服务：
homeDesc3:
- imgs: G500.jpg
  text1: 餐饮酒店娱乐行业
  text2: 系统咨询,订制方案,系统预算,安装调试、系统培训、售后服务。
- imgs: cmpdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 系统规划,订制方案,系统预算,安装调试、系统培训、售后服务。
- imgs: pbdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 系统规划,订制方案,系统预算,安装调试、系统培训、售后服务。
- imgs: cst.jpg
  text1: 餐饮酒店娱乐行业
  text2: 系统规划,订制方案,系统预算,安装调试、系统培训、售后服务。

