name: 庄朋软件
email: jutleo@gmail.com
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
encoding: utf-8
#每页文章数
paginate: 9

WebKeywords: 餐饮管理系统,触摸屏点菜系统,无线点菜宝,酒店管理系统,,客房管理系统,洗浴管理系统,进销存软件
WebDescription: 庄朋软件专注于中小型餐饮酒店娱乐行业智能信息化整体方案提供服务商、6年的行业经验、在为1000家客户服务、餐饮酒店行业软件首选西安庄朋软件、  我要咨询：029-62258029
author:
  name: leo
  email: jutleo@gmail.com
menuitems:
- name:     首页
  subName:  []
  url:      /
  class:    leo-nav-item
- name:     用户体验
  subName:  []
  url:      /2014/02/14/newscenter
  class:    leo-nav-item
- name:     产品中心
  subName:  []
  url:      /2015/01/11/product-center
  class:    leo-nav-item
- name:     我要咨询
  subName:  []
  url:      /2014/02/14/industrycenter
  class:    leo-nav-item
- name:     售后服务
  subName:  []
  url:      /2014/02/14/integrationcenter
  class:    leo-nav-item
- name:     客户案例
  subName:  []
  url:      /2014/02/14/solutioncenter
  class:    leo-nav-item
- name:     软件问答
  subName:  []
  url:      /2014/02/14/baikecenter
  class:    leo-nav-item
- name:     关于我们
  subName:  []
  url:      /contant.html
  url:      /2014/02/14/aboutcenter
  class:    leo-nav-item
pageCatalog:
- name:     方案中心
  code:     solution
- name:     新闻中心
  code:     news
- name:     软件
  code:     soft
- name:     硬件
  code:     hardware
- name:     服务
  code:     service
- name:     快速通道
  code:     away
- name:     最新案例
  code:     casex
- name:     行业资讯
  code:     industry
- name:     品牌活动
  code:     brand

bannerConfig:
- imgs: zp2016.jpg
  text: 
- imgs: zpjd01.jpg
  text: 
- imgs: xpyh.jpg
  text: 
- imgs: jdyd01.jpg
  text: 
- imgs: ydzf01.jpg
  text: 

  homeDescText1: 我们的优势  
homeDesc1:
- imgs: round.gif
  text1: 餐饮行业
  text2: 微信点菜  平板点菜  餐饮收银软件  触摸屏点菜系统  餐饮管理软件  连锁餐饮软件。
- imgs: round.gif
  text1: 酒店宾馆行业
  text2: 客房收银软件  宾馆管理软件  二星~四星酒店软件  连锁酒店一卡通软件。
- imgs: round.gif
  text1: 洗浴娱乐行业
  text2: 洗浴广场管理系统  足浴中心管理软件  桑拿管理系统
- imgs: round.gif
  text1: 零售百货行业
  text2: 超市收银软件  零售进销存软件  行业管理软件  分销管理软件。

homeDescText2: 我们的优势
homeDesc2:
- imgs: canyin.jpg
  text1: 餐饮行业软件
  text2: 我要咨询
- imgs: jdzx01.jpg
  text1: 酒店宾馆行业软件
  text2: 我要咨询
- imgs: jd.jpg
  text1: 洗浴娱乐行业软件
  text2: 我要咨询
- imgs: wxdc01.jpg
  text1: 微信点菜软件
  text2: 我要咨询
- imgs: pbdc01.jpg
  text1: 平板点菜软件
  text2: 我要咨询
- imgs: wxdf01.jpg
  text1: 微信订房
  text2: 我要咨询
homeDescText3: 我们竭诚为您服务：
homeDesc3:
- imgs: G500.jpg 
  text1: 餐饮行业
  text2: 无线点菜软件,无线点菜宝,平板点菜系统,触摸屏管理系统、快餐收银软件、餐饮连锁管理系统、餐饮ERP软件。
- imgs: cmpdc.jpg
  text1: 宾馆酒店娱乐行业
  text2: 宾馆收银软件,客房收银软件,酒店管理软件,星级酒店管理系统、集团一卡通系统。
- imgs: pbdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 宾馆收银软件,客房收银软件,酒店管理系统、连锁酒店管理系统。
- imgs: cst.jpg
  text1: 餐饮酒店娱乐行业
  text2: 洗浴软件、足浴收银软件、洗浴管理系统、足浴管理系统。

