name: 西安庄朋软件
email: jutleo@gmail.com
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
encoding: utf-8
#每页文章数
paginate: 9

WebKeywords: 西安餐饮软件,西安酒店软件,西安财务软件,西安洗浴软件,西安进销存软件、OA办公软件。
WebDescription: 西安餐饮软件/西安酒店软件/西安财务软件。西安庄朋软件专注于中小型餐饮酒店娱乐行业智能信息化整体方案提供服务商、6年的行业经验、每天至少1000家客户在用我们的软件。我要咨询：029-62258029
author:
  name: leo
  email: jutleo@gmail.com
menuitems:
- name:     首页
  subName:  []
  url:      /
  class:    leo-nav-item
- name:     新闻中心
  subName:  []
  url:      /2014/02/14/newscenter
  class:    leo-nav-item
- name:     产品中心
  subName:  []
  url:      /2015/01/11/product-center
  class:    leo-nav-item
- name:     我要咨询
  subName:  []
  url:      /2014/02/14/industrycenter
  class:    leo-nav-item
- name:     售后服务
  subName:  []
  url:      /2014/02/14/integrationcenter
  class:    leo-nav-item
- name:     客户案例
  subName:  []
  url:      /2014/02/14/solutioncenter
  class:    leo-nav-item
- name:     软件问答
  subName:  []
  url:      /2014/02/14/baikecenter
  class:    leo-nav-item
- name:     关于我们
  subName:  []
  url:      /contant.html
  url:      /2014/02/14/aboutcenter
  class:    leo-nav-item
pageCatalog:
- name:     方案中心
  code:     solution
- name:     新闻中心
  code:     news
- name:     软件
  code:     soft
- name:     硬件
  code:     hardware
- name:     服务
  code:     service
- name:     快速通道
  code:     away
- name:     最新案例
  code:     casex
- name:     行业资讯
  code:     industry
- name:     品牌活动
  code:     brand

bannerConfig:
- imgs: zpfw01.jpg
  text: 
- imgs: zpjd01.jpg
  text: 
- imgs: yhjz01.jpg
  text: 
- imgs: jdyd01.jpg
  text: 
- imgs: ydzf01.jpg
  text: 

  homeDescText1: 我们的优势  
homeDesc1:
- imgs: round.gif
  text1: 餐饮行业
  text2: 微信点菜、平板点菜、餐饮收银软件、触摸屏点菜系统、餐饮管理软件、连锁餐饮软件。
- imgs: round.gif
  text1: 酒店宾馆行业
  text2: 客房收银软件、宾馆管理软件、星级酒店软件、连锁酒店系统、一卡通系统、接口开发。
- imgs: round.gif
  text1: 娱乐行业
  text2: 洗浴软件、足浴软件、会所软件、健身房软件。
- imgs: round.gif
  text1: 零售百货行业
  text2: 超市收银软件、进销存软件、OA办公软件、财务软件、连锁分销管理软件。
homeDescText2: 我们的优势
homeDesc2:
- imgs: canyin.jpg
  text1: 餐饮管理软件
  text2: 我要咨询
- imgs: jdzx01.jpg
  text1: 酒店宾馆管理软件
  text2: 我要咨询
- imgs: jd.jpg
  text1: 洗浴娱乐管理软件
  text2: 我要咨询
- imgs: wxdc01.jpg
  text1: 微信点菜软件
  text2: 我要咨询
- imgs: pbdc01.jpg
  text1: 平板点菜软件
  text2: 我要咨询
- imgs: wxdf01.jpg
  text1: 微信订房
  text2: 我要咨询 
-imgs: yycw1.jpg
 text1: 财务软件
 text2: 我要咨询
- imgs: zyoa1.jpg
  text1: 办公OA软件
  text2: 我要咨询
-imgs: wifi1.jpg
  text1: 无线WIFI覆盖
  text2: 我要咨询
homeDescText3: 我们竭诚为您服务：
homeDesc3:
- imgs: G500.jpg 
  text1: 餐饮行业
  text2: 无线餐饮软件,无线点菜宝,平板点菜系统,快餐收银软件、触摸屏管理系统、餐饮连锁管理系统、餐饮ERP软件。
- imgs: cmpdc.jpg
  text1: 宾馆酒店娱乐行业
  text2: 宾馆收银软件,客房收银软件,酒店管理软件,星级酒店管理系统、酒店一卡通系统、接口二次开发。
- imgs: pbdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 宾馆收银软件,客房收银软件,酒店管理系统、连锁酒店管理系统。
- imgs: cst.jpg
  text1: 餐饮酒店娱乐行业
  text2: 洗浴收银软件、足浴收银软件、会员管理软件、会所管理系统、健身房软件。

