name: 庄朋软件
email: jutleo@gmail.com
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
encoding: utf-8
#每页文章数
paginate: 9

WebKeywords: 餐饮管理系统,触摸屏点菜系统,无线点菜宝,酒店管理系统,,客房管理系统,洗浴管理系统,进销存软件
WebDescription: 庄朋软件专注于中小型餐饮酒店娱乐行业智能信息化推荐供应商,餐饮酒店娱乐管理软件行业内第一家注重产品稳定性、精细化管控、数据准确性、注重售后服务的领导品牌,唯一具备软件开发设备开发和生产的供应商，唯一通过ISO9001-2000管理系统认证的供应商。售前咨询：029-89324448
author:
  name: leo
  email: jutleo@gmail.com
menuitems:
- name:     首页
  subName:  []
  url:      /
  class:    leo-nav-item
- name:     软件外包
  subName:  []
  url:      /2014/02/14/newscenter
  class:    leo-nav-item
- name:     产品介绍
  subName:  []
  url:      /2015/01/11/product-center
  class:    leo-nav-item
- name:     售前咨询
  subName:  []
  url:      /2014/02/14/industrycenter
  class:    leo-nav-item
- name:     提供服务
  subName:  []
  url:      /2014/02/14/integrationcenter
  class:    leo-nav-item
- name:     成功案例
  subName:  []
  url:      /2014/02/14/solutioncenter
  class:    leo-nav-item
- name:     软件问答
  subName:  []
  url:      /2014/02/14/baikecenter
  class:    leo-nav-item
- name:     关于我们
  subName:  []
  url:      /contant.html
  url:      /2014/02/14/aboutcenter
  class:    leo-nav-item
pageCatalog:
- name:     方案中心
  code:     solution
- name:     新闻中心
  code:     news
- name:     软件
  code:     soft
- name:     硬件
  code:     hardware
- name:     服务
  code:     service
- name:     快速通道
  code:     away
- name:     最新案例
  code:     casex
- name:     行业资讯
  code:     industry
- name:     品牌活动
  code:     brand

bannerConfig:
- imgs: cpfm01.jpg
  text: 
- imgs: wxts01.jpg
  text: 
- imgs: jdfm1.jpg
  text: 
- imgs: syjd05.jpg
  text: 
- imgs: glwxh.jpg
  text: 

  homeDescText1: 我们的优势  
homeDesc1:
- imgs: round.gif
  text1: 餐饮行业
  text2: 微信点菜  平板点菜  餐饮收银软件  触摸屏点菜系统  餐饮管理软件  连锁餐饮软件。
- imgs: round.gif
  text1: 酒店宾馆行业
  text2: 客房收银软件  宾馆管理软件  二星~四星酒店软件  连锁酒店一卡通软件。
- imgs: round.gif
  text1: 洗浴娱乐行业
  text2: 洗浴广场管理系统  足浴中心管理软件  桑拿管理系统
- imgs: round.gif
  text1: 零售百货行业
  text2: 超市收银软件  零售进销存软件  行业管理软件  分销管理软件。

homeDescText2: 我们的优势
homeDesc2:
- imgs: canyin.jpg
  text1: 餐饮行业软件
  text2: 咨询服务
- imgs: jiudian.jpg
  text1: 酒店宾馆行业软件
  text2: 咨询服务
- imgs: jd.jpg
  text1: 洗浴娱乐行业软件
  text2: 咨询服务
- imgs: wxdc01.jpg
  text1: 微信点菜软件
  text2: 咨询服务
- imgs: pbdc01.jpg
  text1: 平板点菜软件
  text2: 咨询服务
- imgs: wxdf01.jpg
  text1: 微信订房
  text2: 咨询服务
homeDescText3: 我们竭诚为您服务：
homeDesc3:
- imgs: G500.jpg 
  text1: 餐饮酒店娱乐行业
  text2: 无线点菜软件,无线点菜通,平板点菜软件,触摸屏管理系统、餐饮管理软件、餐饮ERP软件。
- imgs: cmpdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 快餐收银软件,火锅收银软件,西餐收银软件,茶楼收银软件、咖啡屋收银软件、迪厅酒店收银软件。
- imgs: pbdc.jpg
  text1: 餐饮酒店娱乐行业
  text2: 快捷酒店收银软件,宾馆收银软件,客房收银软件,酒店管理系统、酒店连锁管理系统、酒店一卡通系统。
- imgs: cst.jpg
  text1: 餐饮酒店娱乐行业
  text2: 洗浴软件、足浴收银软件、洗浴管理系统、足浴管理系统、桑拿收银软件。

